 #author: jayabrata180402@gmail.com
services:
  http-api-gateway:
    build: 
      context: .
      dockerfile: ./apps/http-api-gateway/Dockerfile
      target: development
    command: nodemon --watch src --exec npm run start:dev
    # env_file:
    #   - ./apps/http-api-gateway/.env
    # depends_on:
    #   - postgres    
    ports:
      - "3000:3000"
    volumes:
      - ./apps/http-api-gateway/src:/usr/src/app/src
      - ./apps/http-api-gateway/node_modules:/usr/src/app/node_modules
  users_microservice:
    build: 
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: nodemon --watch src --exec npm run start:dev
    # env_file:
    #   - ./apps/users/.env
    volumes:
      - ./apps/users/src:/usr/src/app/src
      - ./apps/users/node_modules:/usr/src/app/node_modules    
  # oders_microservice:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/orders/Dockerfile
  #     target: development
  #   command: npm run start:dev
  #   # env_file:
  #   #   - ./apps/orders/.env
  #   volumes:
  #     - ./apps/orders/src:/usr/src/app/src
  #     - ./apps/orders/node_modules:/usr/src/app/node_modules
  # restaurants_microservice:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/restaurants/Dockerfile
  #     target: development
  #   command: npm run start:dev
  #   # env_file:
  #   #   - ./apps/restaurants/.env
  #   volumes:
  #     - ./apps/restaurants/src:/usr/src/app/src
  #     - ./apps/restaurants/node_modules:/usr/src/app/node_modules       
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
# postgres database
  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   volumes:
      # - ./postgres-data:/var/lib/postgresql/data