 #author: jayabrata180402@gmail.com
services:
  http-api-gateway:
    build: 
      context: .
      dockerfile: ./apps/http-api-gateway/Dockerfile
      target: development
    command: npm run start:dev http-api-gateway
    env_file:
      - ./apps/http-api-gateway/.env
    ports:
      - "3000:3000"
    volumes:
       - ./apps/http-api-gateway/src:/usr/src/apps/apps/http-api-gateway/src
       - ./libs:/usr/src/apps/libs
       - /usr/src/apps/node_modules
    depends_on:
      - nats
      - postgres
  users_microservice:
    build: 
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    volumes:
       - ./apps/users/src:/usr/src/apps/apps/users/src
       - ./libs:/usr/src/apps/libs
       - /usr/src/apps/node_modules
    depends_on:
      - nats
      - postgres
  oders_microservice:
    build: 
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev oders
    volumes:
       - ./apps/orders/src:/usr/src/apps/apps/orders/src
       - ./libs:/usr/src/apps/libs
       - /usr/src/apps/node_modules
    depends_on:
      - nats
      - postgres
  restaurants_microservice:
    build: 
      context: .
      dockerfile: ./apps/restaurants/Dockerfile
      target: development
    command: npm run start:dev restaurants
    env_file:
      - ./apps/restaurants/.env
    volumes:
       - ./apps/restaurants/src:/usr/src/apps/apps/restaurants/src
       - ./libs:/usr/src/apps/libs
       - /usr/src/apps/node_modules  
  delivery-partners:
    build:
      context: .
      dockerfile: ./apps/delivery-partners/Dockerfile     
      target: development
    command: npm run start:dev delivery-partners
    env_file:
      - ./apps/delivery-partners/.env
    volumes:
       - ./apps/delivery-partners/src:/usr/src/apps/apps/delivery-partners/src
       - ./libs:/usr/src/apps/libs
       - /usr/src/apps/node_modules     
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    #   - '8222:8222'
    # command: -js
# postgres database
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data4/ 
volumes:
  postgres-data:
    external: false